### ISSUE TITLE
Hi, I'm stand your firmware, but I see that on my KS2, I haven't automatic fan speed. It's very dangerous after rebooting, my chips temperatures increase to 100 degrees. And I increase fan speed manually. I think that need to add in next version firmware support automatically correcting fans speed

### ISSUE THREAD

**Issue by vasiliySha** [rdugan/iceriver-oc#1]

**Comment by rdugan** [comment]
Any manual fan speed you set is reapplied after rebooting, which is already an improvement on IceRiver's original firmware.  If you don't set a manual fan speed, then the fan behavior should be no different from the original firmware.

I will look into improving their auto-fan option at some point down the road.

**Comment by vasiliySha** [comment]
Hi Sir, I approved that fan speed after reboot is the same as fan speed before reboot.
