### ISSUE TITLE
Display issue with UpTime

### ISSUE THREAD

**Issue by jjphotos-jeremy** [rdugan/iceriver-oc#10]
Uptime has been calculated wrong:
<img width="407" alt="image" src="https://github.com/rdugan/iceriver-oc/assets/126769075/6281cf08-c7dd-4441-a0b6-2465b9b94028">
Rig up 1 day 30 mins, so for some reason the 24 hasn't changed to 0.
(Using 0.5.0 on a KS0)

**Comment by rdugan** [comment]
heh. yep - i noticed that immediately after release :(
Fix is already implemented, and ready to go for next release.

**Comment by rdugan** [comment]
Latest release (0.6.0) should fix this issue
