### ISSUE TITLE
Cooperation 

### ISSUE THREAD

**Issue by ironwolfm** [rdugan/iceriver-oc#13]
Hi dear , can you make customized framwares for kaspa miners for me?
I am supplier

**Comment by rdugan** [comment]
what sort of customization are you looking for?

**Comment by ironwolfm** [comment]
hello deari need to use my logo and brand name in framwares with 5% devfee for free warranty and support that i give to customers
    On Tuesday, January 23, 2024 at 04:56:41 AM GMT+3:30, rdugan ***@***.***> wrote:  
 
 


what sort of customization are you looking for?
