### ISSUE TITLE
max possible Wattage (after OC) for KS3M

### ISSUE THREAD

**Issue by SammyBoySLO** [rdugan/iceriver-oc#14]
Hi,

what is the maximum Power (in W) for KS3M; (cooling is very well organized), since original power is 3400W?

Thanks and all the best;

Sammy

**Comment by rdugan** [comment]
I don't actually know the PSU rating / efficiency curve, but i would assume somewhere around 90% efficiency at the top end.  This would mean 3400 / 0.9 =~ 3750W line side (at the wall) max.  But also it's probably not the best idea to max out a  PSU that we don't really know the full specs on (unless you have spares).
