### ISSUE TITLE
password error, low hashrate

### ISSUE THREAD

**Issue by mndesign** [rdugan/iceriver-oc#15]
Suddently after 24h-48h the miner reboots and lands on a hashrate of about 94GH
When i try to log in to the miner i get password error.
I then have to reset the miner to get back in

**Comment by rdugan** [comment]
all sorts of people are seeing this behavior, with or without my firmware, so i don't think it's related.  but i can possibly help investigate the issue if you find me in the Kaspa Discord.

**Comment by mndesign** [comment]
sent you a friend request on discord since i cant message you :)
The issue has now evolved, and i cant even get into my KS0 after a factory reset.
I'm only getting the password error issue.
And the hashrate is between 50GH and 108GH

**Comment by rdugan** [comment]
Password errors seem to be from file system corruption, as the miner can't read the password from the appropriate file.  May be fixed by reflashing/resetting to stock so the FS is refreshed.  Closing for now, but will update if anything more concrete is found.
