### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by jjphotos-jeremy** [rdugan/iceriver-oc#19]
When uploading the new firmware, I noticed this typo. This may well already be fixed as it was probably in the previous one, but thought it worth mentioning:
<img width="476" alt="Screenshot 2024-01-30 at 10 01 18" src="https://github.com/rdugan/iceriver-oc/assets/126769075/8a9ace85-9c45-47e8-a690-e8c3c0efe2e4">

(should say automatically)

**Comment by rdugan** [comment]
Haha, i've looked at that page hundreds of times and never noticed it.  Thanks!

**Comment by jjphotos-jeremy** [comment]
I’m sure! The brain is amazing how it sees what you thought you wrote rather than what you actually wrote 😀

**Comment by rdugan** [comment]
addressed in 0.7.0
