### ISSUE TITLE
KSO with 0.6 is working very bad

### ISSUE THREAD

**Issue by marlborotom** [rdugan/iceriver-oc#20]
After 2 days of testing, my 3pcs of KS0 give me less than factory 100gh, ver.0.6, only approx 70-80, very bad.
I’m going back to free solution 160gh, it was much more stable and not paid.
Do something with this bro otherwise people will get Tswift’s solution.

**Comment by Scaneruga** [comment]
+1

**Comment by rdugan** [comment]
is this trolling?  if you actually want a solution, post more details, and/or come to the Kaspa discord, and ask for help.  

This accomplishes nothing.
