### ISSUE TITLE
What is the discord channel the contributors use

### ISSUE THREAD

**Issue by thedonknowsncswic** [rdugan/iceriver-oc#21]
You mentioned these fellows

- BCU79
- Exorcist
- pg13
- Dablacksplash

How can i find them?

**Comment by rdugan** [comment]
Hello... those are all their discord user names.  They are all generally hanging out in the Kaspa Discord:
https://discord.com/invite/kS3SK5F36R

**Comment by rdugan** [comment]
Also, in case you missed it in the main page - don't forget Onslivion :)

**Comment by thedonknowsncswic** [comment]
Thanks very much !!!!
