### ISSUE TITLE
Ks1 not connect webgui help me..

### ISSUE THREAD

**Issue by supersan85** [rdugan/iceriver-oc#22]
After completing the ks1 update process, I could not access the distribution in any way.
The machine cannot be fixed even when I try to reset it. I am in a very bad situation. Can you help me? How can I fix my wrong machine?

**Comment by rdugan** [comment]
Holding down the hardware reset button for 30s generally fixes all problems.  If that doesn't work, come to the Kaspa discord - github is not a great forum for troubleshooting.
