### ISSUE TITLE
KS0 Pro Machine offline 

### ISSUE THREAD

**Issue by tdj1993** [rdugan/iceriver-oc#23]
after install I increased the clock only 15% and machine went offline.. unpluged the miner and plugged in and would go offiline around 3 minutes with no hash. I have the 230 watt power supply and infinity fan. was only looking to get to 280 G/h. Reset to factory Ice River FW and is now online and hashing. Noobie here.. and suggestions? Thanks!

**Comment by rdugan** [comment]
You probably caused the power stages to overheat - you generally need much better airflow and even heatsinks on the power stages to OC KS0Pros.  Join the Kaspa discord and ask around if you need advice on this.
