### ISSUE TITLE
Big difference in sharecounts

### ISSUE THREAD

**Issue by AskJerome** [rdugan/iceriver-oc#25]
I'm using IceRiver Monitor for Tswift and the PBv060ks0Prominer file.
The monitor programs says 7993 accepted and 37 rejected in 27hours or so while the web interface only shows 7143 accepted and 0 rejected. Difference of almost 900 shares, are the shares of Fee time that low of a difficulty that it creating them that much? 

![image](https://github.com/rdugan/iceriver-oc/assets/58232835/e89c6b19-f4dd-4612-8828-fa5c1a0daec2)

**Comment by rdugan** [comment]
It has nothing to do with the fee...  My firmware does it's own tracking for the pool stats, and resets the counters on pool reconnects.  You've clearly reconnected at some point.
