### ISSUE TITLE
KS0 Pro can't start mining on oc firmware

### ISSUE THREAD

**Issue by gike12** [rdugan/iceriver-oc#26]
Hi there,
I just got my ks0 pro a few days ago and when I install the firmware the mining does not start. On the official iceriver firmware it works but on the oc it seem not. On the 0.6.0 it connects to the pool but the Clock stays on 0.00 Mhz and loads but on the 0.7.0 the miner cannot connect to the pool and the Clock stays on 0.00 Mhz. I attach some screenshots maybe that can help.

on 0.6.0
![image](https://github.com/rdugan/iceriver-oc/assets/32132224/e43c0c2a-03b5-4014-bc50-d83970863caf)
![image](https://github.com/rdugan/iceriver-oc/assets/32132224/7dfa3a4b-d9e4-4b34-9461-9ce7d8c1ba22)

on 0.7.0
![image](https://github.com/rdugan/iceriver-oc/assets/32132224/4e5f22db-385a-4b21-9e52-521a955fceca)
![image](https://github.com/rdugan/iceriver-oc/assets/32132224/a8e05925-a009-44f0-afc7-8f7ae3a36004)

And i don't know if its intended but on startup the webgui always says this:
![image](https://github.com/rdugan/iceriver-oc/assets/32132224/0834f354-c378-4b78-b736-5a3532ef72a2)

**Comment by rdugan** [comment]
0.6.0 pool status was unreliable.  this was addressed in 0.7.0.  the status indicators are explained here:
https://github.com/rdugan/iceriver-oc#uptime-and-job-rate-on-pool-status

bottom line, the asic is unable to connect to the pool...  this is an issue w/ your personal network (or less likely, the pool).  Maybe start here:
https://github.com/rdugan/iceriver-oc#known-issues

**Comment by gike12** [comment]
Yes that was my suspicion as well. I had problems with my isp-s router for a long time...  I just ordered a new one and hopefully that will fix it. At that time I use the official firmware.

**Comment by rdugan** [comment]
@gike12 curious... did the new router fix the problem?

**Comment by gike12** [comment]
Yeah it actually did. Just plugged into the new router upgraded the firmware and it instantly connected to the pool. Idk what changed with the new router but I'm happy it worked.
