### ISSUE TITLE
Dev fee schedule

### ISSUE THREAD

**Issue by chad5150** [rdugan/iceriver-oc#3]
what is the dev fee cycle and how long does it run? Great job on the interface! Very cool and its functional. The iceriver interface is a shotty at best. The beta firmware update is an absolute piece of garbage. The save fan setting do not save no matter how long you press save. 
Thank You,
-impressed

**Comment by rdugan** [comment]
Sorry - missed this earlier.  Dev fee is 1% of jobs, running constantly.  Thanks for the feedback... more coming soon!
