### ISSUE TITLE
Cannot connect to antpool

### ISSUE THREAD

**Issue by juanahevia** [rdugan/iceriver-oc#30]
Hi,

with latest 0.7.1 oc firmware my KS1 cannot connect to Antpool....

Regards

**Comment by rdugan** [comment]
there are no recent code changes that would cause this.  These issues are usually caused by internal network conditions.  Please see https://github.com/rdugan/iceriver-oc#known-issues for some places to start troubleshooting.

**Comment by juanahevia** [comment]
Hi,
i have 2 KS0 , 2 KS0PRO, and 1 KS1.
they are all oc to lastest firmware, and none of them can connect antpool. You can see this symbol (!), before the pool on the dashboard. Ive tried everything with no results.
Its not a big problem for me, Im mining on kaspa-pool with no issues,
However I want to share my experience with you in case others have the same problem.

If you re interested I can share printscreens if you like...

Thx !!
Juan
