### ISSUE TITLE
Password error

### ISSUE THREAD

**Issue by mndesign** [rdugan/iceriver-oc#35]
After a couple days all my KS0/Pro will get the "Password error" message.
They are back up again after reset, but this takes time.

Why does this keep happening ?

**Comment by rdugan** [comment]
the iceriver miner software is corrupting an iceriver config file.  this firmware doesn't touch the file, so the only possible relation is if your using unstable OC values.

that being said, i've rewritten the entire login process, so hopefully this can be avoided in the future
