### ISSUE TITLE
KS3M No voltage control

### ISSUE THREAD

**Issue by Telicor** [rdugan/iceriver-oc#37]
I updated my KS3M recently, but it was the only one where my voltage controls were missing. All of the other Kaspa miners work with the software other than the original KS0 from the first batch. They show both Voltage and frequency of the chips, but it does not show on my KS3M. This is an August 2023 KS3M batch, so I do not know if that has the issues listed.

**Comment by rdugan** [comment]
There is no voltage control on any KS3 model
