### ISSUE TITLE
ks3l: how to back to iceriver original firmware?

### ISSUE THREAD

**Issue by mbunal** [rdugan/iceriver-oc#42]
hi, 

how can I back to ice rivers firmware. I flashed already but still pbfarmer running. please help. I can't flash anything right now. neither original not pbfarmer firmware. but still I have ssh connection. and miner working. please help.

after login, I have "Machine is offline" message.

**Comment by rdugan** [comment]
hardware reset.  hold the button for 30s

**Comment by mbunal** [comment]
machine is away from me about 40 kilometers. is it enough restore factory settings button on the bottom?

**Comment by rdugan** [comment]
That's usually how i do it, without any problems.

**Comment by mbunal** [comment]
ok thank you.
