### ISSUE TITLE
Web GUI auto refresh?

### ISSUE THREAD

**Issue by Meier3283** [rdugan/iceriver-oc#47]
Just wondering if it's possible to add an auto-refresh to the miner GUI.  Just a minor usability "nice to have".  
Thanks for considering it!   (Running KS3M, with a KS5L coming)

**Comment by rdugan** [comment]
It's definitely on the todo list.

**Comment by rdugan** [comment]
Latest release (v0.8.1) includes support for KS5L/M, and adds an auto-refresh feature
