### ISSUE TITLE
Job rate and uptime pool and accepted

### ISSUE THREAD

**Issue by Jerobech** [rdugan/iceriver-oc#56]
I have noticed that my job rate is 0.47  is this oke? 

And a other thing i have noticed that the uptime from the pool is reset back to zero once in a while also my accepted gets back to zero.

Do you know why?
Is my latest point caused by mining to your account once in a while?

Best regards
Jero

**Comment by rdugan** [comment]
Job rate should be ~1/s currently, as Kaspa block rate is ~1/s.  Unless you know the pool is purposely rate-limiting jobs (e.g. kaspa-pool), then 0.47 is not 'right'.  But it doesn't necessarily affect your earnings either, as kaspa doesn't have 'late' blocks like normal chains.

Uptime and accepted are reset because your connection was interrupted.

**Comment by Jerobech** [comment]
I am using humpool.com

Job rate is comtiniuos about 0.47



Op wo 15 mei 2024 22:02 schreef rdugan ***@***.***>:

**Comment by rdugan** [comment]
You should ask them why they're not sending all jobs then.

**Comment by rdugan** [comment]
I'm not really sure.  I don't do anything w/ hostname.  You can always set up ssh access and change it.

**Comment by rdugan** [comment]
@Jerobech First I will need to work with someone that has one, so I can't do anything before they ship.  Also, iceriver changes things with every new model, so unfortunately it's not as simple as you might think.  I'm still trying to work through their changes for the ks5l.

**Comment by Jerobech** [comment]
Thanks for your reply,

Please can you give me an update when you are starting on the ks0 ultra?

Best regards

Jeroen

Op vr 7 jun. 2024 18:19 schreef rdugan ***@***.***>:

**Comment by rdugan** [comment]
I can't do anything before they ship.  Also, based on what I'm seeing on the KS5L, it doesn't look like it will be possible to replace the firmware with anything not from IceRiver themselves.

**Comment by Jerobech** [comment]
Here in holland some guys already have the ultra at home

Op di 11 jun. 2024 08:18 schreef rdugan ***@***.***>:
