### ISSUE TITLE
KS0-PRO Crashes when OC passt 16mV or 325mhz offset

### ISSUE THREAD

**Issue by Tob261277** [rdugan/iceriver-oc#57]
My first KS0-Pro works great on your OC running 350GH/s. Now my second one is thermaly modified and PSU also. Startet OC ans worked my way up gradually, but every time I get to either 325mhz or 16mV offset, the miner crashes. Does anybody have any suggestion or do I have an extrem negative example of silicon lottery?

**Comment by rdugan** [comment]
The hardware can only handle what it can handle.  I wouldn't call sub 325mhz (59% OC) 'extreme negative... silicon lottery' by any means.  There are waaaaay worse example than this.

Tuning is best discussed in the Kaspa discords #mining-and-hardware channel, btw.
