### ISSUE TITLE
iceriverminer ELF file

### ISSUE THREAD

**Issue by 2-click** [rdugan/iceriver-oc#60]
I was tinkering around with the awesome work and the original images.
There are 2 bgz files. One containing the web interface and one the backend as exactly one file named "iceriverminer".
When researching I discovered that it’s an ELF file, but where does it come from and how can it be created? Is there any way to see the contents?
Also I was wondering where the actual Linux filesystem is stored. Is it not included in the upgrade files? 

Loving your work and hope to learn more about this awesome field in IT.

**Comment by rdugan** [comment]
An ELF is a linux binary - ie machine code - created by IceRiver when they compiled their source code.  I don't know where the FS is - i would guess in the BIN or image files.

If you don't mind, I'd prefer to reserve this forum for actual issues w/ my fw - the Kaspa discord is probably the best place for discussions about IR stuff (there are people besides me who can probably chime in.)
