### ISSUE TITLE
Ks0 ultra and nicehash

### ISSUE THREAD

**Issue by chad5150** [rdugan/iceriver-oc#64]
New Firmware doesnt seem to play nice with nicehash. My ks0's and ks2 all mine without issue to nicehash on fw 7. The ks0 ultra I can mine to any other pool without issue but when connected to nicehash the machine stops mining.
Thanks

**Comment by rdugan** [comment]
![Screenshot from 2024-07-31 17-42-45](https://github.com/user-attachments/assets/ed95a722-4eaf-421f-aa04-e3871ec1fe3c)

I think you're attributing Nicehash's own problems to the firmware.  I had 2 of 3 connections fail just from a CLI
