### ISSUE TITLE
Kas0 Pro Board1 Power Stage

### ISSUE THREAD

**Issue by 1Knightwing** [rdugan/iceriver-oc#65]
Where exactly is the subject located on the device (board1 power stage)? I’d like to try and use some heat sinks on it to get the temps down, running too close to 125* for comfort!

**Comment by rdugan** [comment]
It's the 4 black chips in front of the chokes (tall boxes).  The ones that everyone (including most youtubers) mistakenly refer to as mosfets (there are two mosfets inside the power stages).

**Comment by 1Knightwing** [comment]
Thanks! Got a heat sink (6x6x5mm) on each of those already so guess I’ve done all I can to mitigate that issue, apart from maybe stronger fans. Temps there range from 108-121* C, with clock at 831mHz for a stable 300-320 gh/s, my goal range. I gather they can operate at 125* C.
