### ISSUE TITLE
I need help with ks0 ultra I have a firmware upgrade but something went wrong and now I can't access its ip page anymore can someone help me

### ISSUE THREAD

**Issue by Hienishere** [rdugan/iceriver-oc#66]

**Comment by BeardoGuy** [comment]
The SSl certificate expires when you update to this firmware, just open up a different browser and access the same ip (you might get insecure connection warning-go to advanced and click on continue browsing)

**Comment by bm3-maker** [comment]
Same Problem here. @BeardoGuy this doesnt work for me

**Comment by craigc403** [comment]
try another browser

**Comment by cmueller79** [comment]
Hello i have same problem with one device after upgrade, i testing other Browser, clear caches and other PC i can get any Connection via Browser, but I testing IceriverMonitor i can see the KS Ultra works an is connectet to Pool. 
is there any other way to reflash  the KS Ultra ?
