### ISSUE TITLE
KS3M

### ISSUE THREAD

**Issue by mb-pro69** [rdugan/iceriver-oc#69]
Hello, i installed your firmware on my ks3m today but it doesn't run, i can't access now to asic configuration page. I use static IP for this asic. If i do a hard reset and come back to the official firmware, and try to access again to configuaration page (same static IP adress), it's ok, no problem !
But with the OC firmware impossible to connect me...
I've read the known issues in README file but it haven't helped me.
Can you help me please ?

**Comment by mb-pro69** [comment]
Hello rdugan, first thanks you for your answer and your help. Excuse me, english isn't my first language... I mean, it uses a static IP in my router (FAI) but, in asic settings, it's on DHCP... I've already try mozilla and chrome bronwsers.
 I don't know wat i can verify more?
![image](https://github.com/user-attachments/assets/521ea7c1-de97-483f-a01a-7a3d7a31158e)
![image](https://github.com/user-attachments/assets/acb5452d-8f4b-4fed-a1c6-e337e6a6d2fe)

**Comment by mb-pro69** [comment]
with official firmware, i access again to configuration page:
![image](https://github.com/user-attachments/assets/7706635f-6dd6-4131-8abf-8751d63ca248)

**Comment by rdugan** [comment]
There are only two reasons I know of why you wouldn't be able to access the page.  The first is that it's the wrong IP, but your setup looks like it should be ok.  

The second is that my firmware is now using https, and the TLS certificate is generated on the machine, rather than by a known authority, so it will be untrusted until/unless you import the CA certificate into your browser.  But in that case you should still have a warning in your browser that allows you to 'Accept the Risk and Continue' - which is clearly not present your case.  

Try 'force refreshing' the page (i.e. load without cache), or clearing your cache then reloading.  If that doesn't work, I can only suggest to do a hardware factory reset (hold the button for 40s) then reupload the firmware, in case the machine is still using old network settings.

**Comment by rdugan** [comment]
Also, I should mention that there is a bug in the KS3M clock setting mechanism, so if you were using this to over/underclock your ASIC, i would recommend using 0.7.1 until I can release an update.

**Comment by mb-pro69** [comment]
Good evening and thank you for this information. I just did a hard reset, I emptied the cache, I tried to open the page in a private firefox window, I emptied the cache but nothing to do, it's strange :(
![image](https://github.com/user-attachments/assets/f244dcce-a78b-47f9-a932-6ea2fc8de959)

**Comment by mb-pro69** [comment]
the firmware i am trying to use is 5977449_ks3m_miner.bgz

**Comment by rdugan** [comment]
I have no idea what that firmware is.  It's not mine.  So it won't be using https

**Comment by mb-pro69** [comment]
no it's the firmware i found in your Github, you affraid me, i verify now

**Comment by mb-pro69** [comment]
Isn't it this firmware i may use ?
![image](https://github.com/user-attachments/assets/91b16103-7ee1-439b-958c-d5ef7d7424e6)

**Comment by rdugan** [comment]
No.  that's "extras" - ie related software, not mine.  As the folder name says, these are the original firmware files from IceRiver.  

My firmware is in the releases section:

https://github.com/rdugan/iceriver-oc/releases

**Comment by mb-pro69** [comment]
ok sorry, but in these firmwares, which one is for ks3m ?
![image](https://github.com/user-attachments/assets/2dab3760-f20c-4f32-b3d8-2bda3937cd7a)

**Comment by rdugan** [comment]
There is no 0.8.0 version available at this time.  I've removed it because of the bug I mentioned above.  You can use 0.7.1 until I release the fix in 0.8.1.

**Comment by mb-pro69** [comment]
i am so sorry, so i was using the bad firmware :( Thanks a lot for your help. I am going to try it:
![image](https://github.com/user-attachments/assets/838473be-48a9-4993-a2c0-eceeb18c2e09)

 have a nice day ;)

**Comment by rdugan** [comment]
No problem... I'll update/close this issue when i release the new version.  Cheers!

**Comment by rdugan** [comment]
New release (v0.8.1) has been pushed, including KS3L/M builds

**Comment by mb-pro69** [comment]
Good job. Thanks fo all :)

**Comment by mb-pro69** [comment]
Finally, VOLTAGE CONTROL IS NOT AVAILABLE FOR KS3/M IN THIS VERSION ?.

**Comment by rdugan** [comment]
There is no tuneable power circuitry on KS3* or KS5* models.

**Comment by mb-pro69** [comment]
ok, you know better than me :) Thanks
