### ISSUE TITLE
machine is offline

### ISSUE THREAD

**Issue by Kashpero** [rdugan/iceriver-oc#7]
<img width="799" alt="image" src="https://github.com/rdugan/iceriver-oc/assets/155971205/871a9249-d17e-4873-a666-aa299de3825e">

Can you help with this?
Because pool see my miner

**Comment by rdugan** [comment]
Did this resolve itself?

**Comment by Kashpero** [comment]
No, just return to factory settings

**Comment by rdugan** [comment]
Ok.  If you want to try to get it working, please find me in the Kaspa discord (username: pbfarmer)
