### ISSUE TITLE
Fan control reverts to asic setting on power loss

### ISSUE THREAD

**Issue by 1Knightwing** [rdugan/iceriver-oc#73]
I generally run my PB pros on 100% fixed fan as my OCs run close to the 125* edge. When power is interrupted, they reset to the asic control setting, thus lowering rpm’s and dangerously increasing power board temps. The miner control panel still displays that they are fixed and 100% tho not the case.

**Comment by rdugan** [comment]
I can't control what IceRiver does in the background.  If they decide to randomly switch fan modes, my fw can't do anything about it, unless it's constantly checking the speed every X seconds.  Which is exactly what my temp target fan mode does - so just use that.

**Comment by 1Knightwing** [comment]
Thanks! Thought about that but since there are 3 separate modes, fixed, temp, and asic, I assumed it would restart on asic with either. Will give it a try!Sent from my iPhoneOn Aug 16, 2024, at 2:54 PM, rdugan ***@***.***> wrote:﻿
I can't control what IceRiver does in the background.  If they decide to randomly switch fan modes, my fw can't do anything about it, unless it's constantly checking the speed every X seconds.  Which is exactly what my temp target fan mode does - so just use that.

**Comment by rdugan** [comment]
It's always restarting on auto.  My firmware reapplies your settings a few minutes after startup.  But IR can always override that again later, unless i have a loop constantly reapplying, like in the target temp mode.

**Comment by 1Knightwing** [comment]
Got it! Prob doesn’t matter what the target temp is, long as min is 100%?Sent from my iPhoneOn Aug 16, 2024, at 5:00 PM, rdugan ***@***.***> wrote:﻿
It's always restarting on auto.  My firmware reapplies your settings a few minutes after startup.  But IR can always override that again later, unless i have a loop constantly reapplying, like in the target temp mode.
