### ISSUE TITLE
Udate failed on KS0 Ultra

### ISSUE THREAD

**Issue by marchapunkt** [rdugan/iceriver-oc#76]
Hi, 

I just tried to install the latest version on my new KS0 Ultra but it says "failed" all the time. 
Tried factory reset, update to latest original Firmware, redownload file from GitHub. 

Is there any way to check Logs to find out why the Upadate fails?

**Comment by rdugan** [comment]
Pretty much every time i've heard this, it's because someone has some other tool pinging the ASIC constantly

**Comment by marchapunkt** [comment]
You were right! It was my Network Monitoring System...
