### ISSUE TITLE
0.8.1 KS0 Ultra Board Temp Value Empty After Reboot

### ISSUE THREAD

**Issue by ghost** [rdugan/iceriver-oc#77]
With the Fan Mode of Target Temp the Board Temp value field is empty after I rebooted my two KS0 Ultras. Their was a value after the 0.8.1 update and I didn't change that, I had only changed the chip temp before the reboot.

**Comment by rdugan** [comment]
There is never a default value for either target temp.  And you cannot save the fan settings without entering a value for both options.
