### ISSUE TITLE
No hashrate without fans connected?

### ISSUE THREAD

**Issue by Brennerlein** [rdugan/iceriver-oc#82]
Hello everyone,

Today I finally managed to modify my ULTRAs. As with the PROs, I put copper heat sinks on the mosfets and removed the two 40mm fans and closed the openings.

Unfortunately, the miner now does nothing, or rather it fluctuates between 1 and 3 GH/s.

I suspect that this is due to the fans not being connected, but this has always worked with the PROs.

![image](https://github.com/user-attachments/assets/fc0dde3d-194b-4307-9a53-c132e667a87e)

**Comment by rdugan** [comment]
Please see https://github.com/rdugan/iceriver-oc/issues/72
